//
//  ShowWeatherDetailModels.swift
//  WeatherApplication
//
//  Created by dsadaoui on 11/08/2020.
//  Copyright (c) 2020 djabir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//



import WeatherApi

enum WeatherDetail {
    enum Success {
        struct Response {
            var currentWeather: Current
        }
        struct ViewModel {
            var icon: String?
            var description: String?
            var temp: String?
            var sunrise: String?
            var sunset: String?
            var feelslike: String?
            var pressure: String?
            var humidity: String?
            var visibility: String?
            var winspeed: String?
        }
    }
    enum Failure {
        struct Response {
            var error: Error
        }
        struct ViewModel {
            var error: String
        }
    }
}

