//
//  ShowWeatherDetailViewController.swift
//  WeatherApplication
//
//  Created by dsadaoui on 11/08/2020.
//  Copyright (c) 2020 djabir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowWeatherDetailDisplayLogic: class {
    func displaySomething(viewModel: ShowWeatherDetail.Something.ViewModel)
}

class ShowWeatherDetailViewController: UIViewController, ShowWeatherDetailDisplayLogic {
    var interactor: ShowWeatherDetailBusinessLogic?
    var router: (NSObjectProtocol & ShowWeatherDetailRoutingLogic & ShowWeatherDetailDataPassing)?
    
    // MARK: Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    required init?(coder aDecoder: NSCoder){
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        configure()
    }
    
    // MARK: configure a view
    func configure(){
        let request = ShowWeatherDetail.Something.Request()
        interactor?.doSomething(request: request)
    }
    // MARK: Setup
    private func setup() {
        let viewController = self
        let interactor = ShowWeatherDetailInteractor()
        let presenter = ShowWeatherDetailPresenter()
        let router = ShowWeatherDetailRouter()
        let worker = ShowWeatherDetailWorker()
        interactor.worker = worker
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: Display
    func displaySomething(viewModel: ShowWeatherDetail.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
