//
//  ShowWeatherDetailInteractor.swift
//  WeatherApplication
//
//  Created by dsadaoui on 11/08/2020.
//  Copyright (c) 2020 djabir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol ShowWeatherDetailBusinessLogic {
  func doSomething(request: ShowWeatherDetail.Something.Request)
}

protocol ShowWeatherDetailDataStore {
  //var name: String { get set }
}

class ShowWeatherDetailInteractor: ShowWeatherDetailBusinessLogic, ShowWeatherDetailDataStore {
  var presenter: ShowWeatherDetailPresentationLogic?
  var worker: ShowWeatherDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ShowWeatherDetail.Something.Request) {
    worker?.doSomeWork()
    let response = ShowWeatherDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
