//
//  ShowWeatherDetailWorker.swift
//  WeatherApplication
//
//  Created by dsadaoui on 11/08/2020.
//  Copyright (c) 2020 djabir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import WeatherApi
protocol ShowWeatherDetailWorkerProtocol {
    var weatherService: WeatherService {get set}
    func getCurrentAndForcastWeather(lat: Double, lon: Double, completion: @escaping (Result<Current,WeatherError>)->Void)
}
class ShowWeatherDetailWorker: ShowWeatherDetailWorkerProtocol{
    // MARK: Vars
    var weatherService = WeatherService.shared
    
    // MARK: Works
    func getCurrentAndForcastWeather(lat: Double, lon: Double, completion: @escaping (Result<Current, WeatherError>) -> Void) {
        weatherService.getCurrentAndForcastWeather(lat: String(lat), lon: String(lon)) { (result) in
            DispatchQueue.main.async {
                completion(result)
            }
        }
    }
}
