//
//  ShowWeatherListInteractor.swift
//  WeatherApplication
//
//  Created by dsadaoui on 11/08/2020.
//  Copyright (c) 2020 djabir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import WeatherApi

protocol ShowWeatherListBusinessLogic {
    var currentCity: CityEntity? { get set }
    var cities: [CityEntity] {get set}
    func getAllCities()
}

protocol ShowWeatherListDataStore {
    var currentCity: CityEntity? { get set }
}

class ShowWeatherListInteractor: ShowWeatherListBusinessLogic, ShowWeatherListDataStore {
    // MARK: Vars
    var cities: [CityEntity] = []
    var presenter: ShowWeatherListPresentationLogic?
    var worker: ShowWeatherListWorker?
    var currentCity: CityEntity?
    
    // MARK: Do something
    func getAllCities() {
        worker?.fetchCities(completion: { (cities) in
            self.cities = cities ?? []
            self.presenter?.presentCities()
        })
    }
}
