//
//  ShowWeatherListPresenter.swift
//  WeatherApplication
//
//  Created by dsadaoui on 11/08/2020.
//  Copyright (c) 2020 djabir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol ShowWeatherListPresentationLogic {
    func presentCities()
}

class ShowWeatherListPresenter: ShowWeatherListPresentationLogic {
    //MARK: Vars
    weak var viewController: ShowWeatherListDisplayLogic?
    
    // MARK: Present views
    func presentCities(){
        viewController?.displayCities()
    }
}
