//
//  ShowWeatherListRouter.swift
//  WeatherApplication
//
//  Created by dsadaoui on 11/08/2020.
//  Copyright (c) 2020 djabir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowWeatherListRoutingLogic {
    func routeToWeatherDetail(segue: UIStoryboardSegue?)
}

protocol ShowWeatherListDataPassing {
    var dataStore: ShowWeatherListDataStore? { get }
}

class ShowWeatherListRouter: NSObject, ShowWeatherListRoutingLogic, ShowWeatherListDataPassing {
    weak var viewController: ShowWeatherListViewController?
    var dataStore: ShowWeatherListDataStore?
    
    // MARK: Routing
    func routeToWeatherDetail(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! ShowWeatherDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowWeatherDetail(source: dataStore!, destination: &destinationDS)
        }
    }
    
    // MARK: Passing data
    func passDataToShowWeatherDetail(source: ShowWeatherListDataStore, destination: inout ShowWeatherDetailDataStore)
    {
        destination.currentCity = source.currentCity
    }
}
