//
//  ShowWeatherListPresenter.swift
//  WeatherApplication
//
//  Created by dsadaoui on 11/08/2020.
//  Copyright (c) 2020 djabir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol ShowWeatherListPresentationLogic {
  func presentSomething(response: ShowWeatherList.Something.Response)
}

class ShowWeatherListPresenter: ShowWeatherListPresentationLogic {
  weak var viewController: ShowWeatherListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ShowWeatherList.Something.Response) {
    let viewModel = ShowWeatherList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
