//
//  AddCityPresenter.swift
//  WeatherApplication
//
//  Created by dsadaoui on 11/08/2020.
//  Copyright (c) 2020 djabir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol AddCityPresentationLogic {
  func presentSomething(response: AddCity.Something.Response)
}

class AddCityPresenter: AddCityPresentationLogic {
  weak var viewController: AddCityDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: AddCity.Something.Response) {
    let viewModel = AddCity.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
