//
//  AddCityRouter.swift
//  WeatherApplication
//
//  Created by dsadaoui on 11/08/2020.
//  Copyright (c) 2020 djabir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddCityRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol AddCityDataPassing {
  var dataStore: AddCityDataStore? { get }
}

class AddCityRouter: NSObject, AddCityRoutingLogic, AddCityDataPassing {
  weak var viewController: AddCityViewController?
  var dataStore: AddCityDataStore?
}
