//
//  AddCityInteractor.swift
//  WeatherApplication
//
//  Created by dsadaoui on 11/08/2020.
//  Copyright (c) 2020 djabir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol AddCityBusinessLogic {
    func addCity(city: String, lat: Double, lon: Double)
}

protocol AddCityDataStore {
}

class AddCityInteractor: AddCityBusinessLogic, AddCityDataStore {
    // MARK: Vars
    var presenter: AddCityPresentationLogic?
    var worker: AddCityWorker?
    
    // MARK: Do something
    func addCity(city: String, lat: Double, lon: Double) {
        worker?.saveCity(cityName: city, lat: lat, lon: lon, completion: { (city, error) in
            if let error = error {
                let response = AddCity.Failure.Response(error: error)
                self.presenter?.presentAddCityFailure(response: response)
            } else {
                self.presenter?.presentAddCitySuccess()
            }
        })
    }
}
