//
//  AddCityWorker.swift
//  WeatherApplication
//
//  Created by dsadaoui on 11/08/2020.
//  Copyright (c) 2020 djabir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import WeatherApi

protocol AddCityWorkerProtocol {
    var weatherDataManager: DataManager { get set}
    func saveCity(cityName: String,lat: Double, lon: Double, completion: @escaping(CityEntity?, WeatherError?)-> Void)
}
class AddCityWorker: AddCityWorkerProtocol {
    // MARK: Vars
    var weatherDataManager:DataManager = WeatherDataManager.shared
    
    // MARK: Works
    func saveCity(cityName: String, lat: Double, lon: Double, completion: @escaping (CityEntity?, WeatherError?) -> Void) {
        weatherDataManager.createCity(name: cityName, lat: lat, lon: lon) { (city, error) in
            DispatchQueue.main.async {
                completion(city,error)
            }
        }
    }
}
