//
//  AddCityInteractor.swift
//  WeatherApplication
//
//  Created by dsadaoui on 11/08/2020.
//  Copyright (c) 2020 djabir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol AddCityBusinessLogic {
  func doSomething(request: AddCity.Something.Request)
}

protocol AddCityDataStore {
  //var name: String { get set }
}

class AddCityInteractor: AddCityBusinessLogic, AddCityDataStore {
  var presenter: AddCityPresentationLogic?
  var worker: AddCityWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: AddCity.Something.Request) {
    worker?.doSomeWork()
    let response = AddCity.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
