//
//  AddCityPresenter.swift
//  WeatherApplication
//
//  Created by dsadaoui on 11/08/2020.
//  Copyright (c) 2020 djabir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol AddCityPresentationLogic {
    func presentAddCityFailure(response: AddCity.Failure.Response)
    func presentAddCitySuccess()
}

class AddCityPresenter: AddCityPresentationLogic {
    // MARK: Vars
    weak var viewController: AddCityDisplayLogic?
    
    // MARK: Present something
    func presentAddCityFailure(response: AddCity.Failure.Response){
        let viewModel = AddCity.Failure.ViewModel(error: response.error.localizedDescription)
        self.viewController?.displayAddCityFailure(viewModel: viewModel)
    }
    func presentAddCitySuccess(){
        self.viewController?.displayAddCitySuccess()
    }
}

